"""
Django settings for redditscraper project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
from django.conf import settings

if not settings.DEBUG:
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    import os
    print "Production"

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'd=kuaqj!&nm@*^g4a_l-io+&+mm73s#=dt!&s0%i39*(2#fsm)'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = ['patstocklin.webfactional.com']


    # Application definition

    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'crispy_forms',
        'searchsubreddit',
    )

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'django.middleware.security.SecurityMiddleware',
    )

    ROOT_URLCONF = 'redditscraper.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, "templates")],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    # FILE_UPLOAD_HANDLERS = (
    #     "progressbarupload.uploadhandler.ProgressBarUploadHandler",
    #     "django.core.files.uploadhandler.MemoryFileUploadHandler",
    #     "django.core.files.uploadhandler.TemporaryFileUploadHandler",
    # )

    WSGI_APPLICATION = 'redditscraper.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/1.8/ref/settings/#databases

    from .db_password import DBPASS

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': "redditscraper",
            'USER': "patstocklin",
            'PASSWORD': DBPASS,
        }
    }


    # Internationalization
    # https://docs.djangoproject.com/en/1.8/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.8/howto/static-files/

    STATIC_URL = '/static/'

    #What is going to be served when we go 
    #Want to keep them separate from the project
    #We don't want to directly update to Static Root, let DJANGO do it
    STATIC_ROOT = '/home/patstocklin/webapps/redditscraper_static'

    #Where the static things exist when we serve them
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static_in_pro", "our_static"),
        # os.path.join(BASE_DIR, "static_in_env")
    )

    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/home/patstocklin/webapps/redditscraper_media'

    CRISPY_TEMPLATE_PACK = 'bootstrap3'
